window.CELLZONE_SHIPPING = {
  // Envío gratis desde este subtotal:
  freeFrom: 2500,

  // AGREGA O QUITA VENDEDORES AQUÍ:
  sellers: ["Mayra", "Rigo", "Edith", "Otro"],

  // UNA SOLA LISTA DE ENVÍOS PARA TODOS LOS VENDEDORES:
  locations: [
    { text: "15 DE SEPTIEMBRE", cost: 80 },
    { text: "ALTOS DE LOARQUE (MIRADOR)", cost: 90 },
    { text: "ALTOS DE TONCONTIN", cost: 80 },
    { text: "AMERICA", cost: 80 },
    { text: "CASCADAS CITY", cost: 80 },
    { text: "CIUDAD NUEVA", cost: 80 },
    { text: "COLONIA LOARQUE", cost: 90 },
    { text: "COLONIA SATELITE", cost: 90 },
    { text: "EL SAUCE", cost: 90 },
    { text: "LA ARBOLEDA", cost: 100 },
    { text: "LA CATOLICA", cost: 90 },
    { text: "LA CONCEPCION", cost: 100 },
    { text: "LA GODOY", cost: 80 },
    { text: "LA MIRAFLores", cost: 80 },
    { text: "LAS CASITAS", cost: 100 },
    { text: "LAS COLINAS", cost: 80 },
    { text: "LAS HADAS", cost: 80 },
    { text: "LAS LOMAS", cost: 80 },
    { text: "LAS MINITAS", cost: 80 },
    { text: "LAS UVAS", cost: 90 },
    { text: "LOMA LINDA", cost: 80 },
    { text: "LOMA VERDE", cost: 80 },
    { text: "LOMAS DE TILOARQUE", cost: 80 },
    { text: "LOMAS DEL TONCONTIN", cost: 80 },
    { text: "MIRADOR DE LOS ANGELES", cost: 100 },
    { text: "MIRAMONTES", cost: 80 },
    { text: "PALMA REAL", cost: 90 },
    { text: "PERIODISTA", cost: 80 },
    { text: "PRADOS UNIVERSITARIOS", cost: 90 },
    { text: "RESIDENCIA PLAZA", cost: 80 },
    { text: "RESIDENCIAL CENTROAMERICA", cost: 80 },
    { text: "RESIDENCIAL EUCALIPTO", cost: 90 },
    { text: "RESIDENCIAL LAS CASITAS", cost: 120 },
    { text: "RESIDENCIAL LOS HIDALGOS", cost: 100 },
    { text: "RESIDENCIAL LOS ROBLES", cost: 90 },
    { text: "RESIDENCIAL VENECIA", cost: 80 },
    { text: "ROBLE OESTE", cost: 90 },
    { text: "SAN IGNACIO", cost: 80 },
    { text: "SAN SEBASTIAN", cost: 130 },
    { text: "VICTOR F. ARDON", cost: 80 },
    { text: "ALTOS DE LA GRANJA", cost: 80 },
    { text: "ALTOS DE LA JOYA", cost: 80 },
    { text: "BELLA ORIENTE", cost: 90 },
    { text: "BLV JUAN PABLO SEGUNDO", cost: 80 },
    { text: "BO EL CENTRO", cost: 80 },
    { text: "BO LA BOLSA", cost: 80 },
    { text: "BO MORAZAN", cost: 80 },
    { text: "BOULERVAR KUWAIT", cost: 80 },
    { text: "COL 3 CAMINOS", cost: 80 },
    { text: "COL 15 DE SEPTIEMBRE", cost: 80 },
    { text: "COL BERNARDO DACI", cost: 80 },
    { text: "COL KENNEDY", cost: 80 },
    { text: "COL LUIS LANDA", cost: 80 },
    { text: "COL MAYANGLE", cost: 80 },
    { text: "COL SAN ANGEL", cost: 80 },
    { text: "COL TEPEYAC", cost: 80 },
    { text: "COL SATELITE", cost: 90 },
    { text: "COLONIA LA VEGA", cost: 80 },
    { text: "ECOVIVIENDA", cost: 90 },
    { text: "EL ALAMO", cost: 80 },
    { text: "EL HOGAR", cost: 80 },
    { text: "EL PRADO", cost: 80 },
    { text: "LA ALAMEDA", cost: 80 },
    { text: "LA FLORENCIA", cost: 80 },
    { text: "LA GRANJA", cost: 80 },
    { text: "LA HUMUYA", cost: 80 },
    { text: "LA MARADIAGA", cost: 80 },
    { text: "VENECIA", cost: 90 },
    { text: "EL LADO DE LA QUESADA", cost: 100 },
    { text: "LA ULLOA", cost: 100 },
    { text: "ORILLA DEL ANILLO EL DIVINO PARAISO", cost: 100 },
    { text: "LA SAN MIGUEL", cost: 100 },
    { text: "LA TRAVESÍA (CALLE PRINCIPAL, NO SE PASA DEL PALO)", cost: 100 },
    { text: "CERRO GRANDE ZONA 1/2/3", cost: 90 },
    { text: "CERRO GRANDE ZONA 4", cost: 100 },
    { text: "CERRO GRANDE ZONA 8", cost: 120 },
    { text: "LA RONDA", cost: 90 },
    { text: "EL BOSQUE", cost: 100 },
    { text: "BUENOS AIRES (CALLE PRINCIPAL)", cost: 100 },
    { text: "EL MANCHEN", cost: 90 },
    { text: "21 DE OCTUBRE", cost: 100 },
    { text: "MONTELIMAR", cost: 80 },
    { text: "GERMANIA", cost: 120 }
  ]
};
