window.CELLZONE_SHIPPING = {
  // Envío gratis desde este subtotal:
  freeFrom: 2500,

  // AGREGA O QUITA VENDEDORES AQUÍ:
  sellers: ["Mayra", "Rigo", "Edith", "Otro"],

  // UNA SOLA LISTA DE ENVÍOS PARA TODOS LOS VENDEDORES:
  locations: [
    { text: "15 DE SEPTIEMBRE", cost: 90 },
    { text: "Colonia Miramontes", cost: 100 },
    { text: "ALTOS DE LOARQUE (MIRADOR)", cost: 90 },
    { text: "ALTOS DE TONCONTIN", cost: 90 },
    { text: "AMERICA", cost: 90 },
    { text: "CASCADAS MALL", cost: 100 },
    { text: "CITY MALL", cost: 100 },
    { text: "CIUDAD NUEVA", cost: 90 },
    { text: "COLONIA LOARQUE", cost: 90 },
    { text: "COLONIA SATELITE", cost: 90 },
    { text: "EL SAUCE", cost: 90 },
    { text: "LA ARBOLEDA", cost: 90 },
    { text: "LA CATOLICA", cost: 90 },
    { text: "LA CONCEPCION", cost: 100 },
    { text: "LA GODOY", cost: 90 },
    { text: "LOS HIDALGOS", cost: 90 },
    { text: "SAN IGNACIO", cost: 100 },
    { text: "SAN SEBASTIAN", cost: 140 },
    { text: "BO EL CENTRO", cost: 100 },
    { text: "BO LA BOLSA", cost: 100 },
    { text: "BO MORAZAN", cost: 100 },
    { text: "BLV JUAN PABLO SEGUNDO", cost: 100 },
    { text: "LAS UVAS", cost: 90 },
    { text: "ALTOS DE LA GRANJA", cost: 100 },
    { text: "EL ALAMO", cost: 100 },
    { text: "EL HOGAR", cost: 100 },
    { text: "EL PRADO", cost: 100 },
    { text: "LA ALAMEDA", cost: 100 },
    { text: "COLONIA LA VEGA", cost: 90 },
    { text: "ECOVIVIENDA", cost: 100 },
    { text: "LA FLORENCIA", cost: 100 },
    { text: "LA HUMUYA", cost: 100 },
    { text: "LA GRANJA", cost: 100 },
    { text: "VENECIA", cost: 100 },
    { text: "Cero grande hasta la zona 4", cost: 120 },
    { text: "San Miguel", cost: 100 },
    { text: "La ronda", cost: 100 },
    { text: "Buenos Aires", cost: 110 },
    { text: "La campaña", cost: 100 },
    { text: "Guanacaste", cost: 100 },
    { text: "21 de octubre", cost: 110 },
    { text: "21 de febrero", cost: 100 },
    { text: "La cañada", cost: 100 },
    { text: "El hato", cost: 100 },
    { text: "El trapiche", cost: 100 },
    { text: "Suyapa solo abajo calle principal", cost: 100 },
    { text: "El divino paraíso solo en el anillo", cost: 110 },
    { text: "La ulloa solo orilla del anillo", cost: 100 },
    { text: "Carrizal", cost: 100 },
    { text: "Moll premier", cost: 100 },
    { text: "Torocagua", cost: 100 },
    { text: "Colonia villeda Morales", cost: 0 },
    { text: "Complejo Río lindo la Vega", cost: 100 },
    { text: "Calle los alcaldes enfrente de la naval a la par macdell", cost: 100 },
    { text: "Brisas del valle calle principal", cost: 110 },
    { text: "Plaza ciudad Nueva por calle los alcaldes", cost: 90 },
    { text: "Villa olímpica", cost: 100 },
    { text: "Al durazno salida al norte por la posta", cost: 170 },
    { text: "Detrás de Banco Central por chiminique", cost: 100 },
    { text: "Sector el sauce por pricesmart", cost: 90 },
    { text: "Pedregal", cost: 100 },
    { text: "UNITEC", cost: 100 },
    { text: "Barrio bella vista", cost: 100 },
    { text: "Predregalito BO del norte", cost: 100 },
    { text: "Conatel", cost: 100 },
    { text: "Barrio Abajo", cost: 100 },
    { text: "Plaza miraflores", cost: 100 },
    { text: "Plaza portal del bosque Frente a restaurante IL Padrino", cost: 90 },
    { text: "Gasolinera Texaco en el desvío a Mateo", cost: 90 },
    { text: "Nueva capital (hasta el anillo orilla)", cost: 110 },
    { text: "Colonia Humuya por el hospital Dime", cost: 100 },
    { text: "Colonia la rosa por citymall por antigua dipsa", cost: 100 },
    { text: "Divino paraiso se entrega a orilla del anillo", cost: 110 },
    { text: "Universidad Pedagogica", cost: 100 },
    { text: "Plaza Loarque", cost: 90 },
    { text: "Colonia Villanueva en el puente peatonal de la honduras", cost: 100 },
    { text: "Lomas del Guijarro Sur", cost: 100 },
    { text: "Más abajito del mall premiere por la Polo en el desvío", cost: 100 },
    { text: "Colonia Loma la Minita por la 21 de octubre", cost: 120 },
    { text: "Residencial plaza", cost: 100 },
    { text: "Metromall", cost: 90 },
    { text: "Ransa anillo periférico por pricemart del sauce", cost: 90 },
    { text: "Residencial La Cañada", cost: 100 },
    { text: "Colonia Álamo", cost: 100 },
    { text: "Cerro Grande zona 8", cost: 160 },
    { text: "Novacentro", cost: 100 },
    { text: "Residencial El Sauce", cost: 90 },
    { text: "Kennedy primera entrada", cost: 100 },
    { text: "Colonia Arturo Quezada (calle principal)", cost: 100 },
    { text: "Residencial Bella Oriente sector 8B", cost: 100 },
    { text: "Colonia Quezada", cost: 100 },
    { text: "Hato de En Medio (cualquier sector)", cost: 100 },
    { text: "Colonia La Cañada calle principal por arenera", cost: 100 },
    { text: "Colonia Miraflores por iglesia católica (mercadito Cristian Diego)", cost: 100 },
    { text: "Lomas del Guijarro por el Sagrado Corazón", cost: 100 },
    { text: "Complejo policial San Miguel por el puente El Dólar", cost: 100 },
    { text: "Centro de Tegucigalpa por la catedral", cost: 100 },
    { text: "Residencial Roble Oeste", cost: 90 },
    { text: "Tecnicentro La Bendición frente a Ecoplaza", cost: 100 },
    { text: "Hospital Escuela portón 1", cost: 100 },
    { text: "Plaza Loarque (Gallo Más Gallo)", cost: 90 },
    { text: "DPI Kennedy primera entrada", cost: 100 },
    { text: "Carretera al Picacho adelante de Casa de Piedra", cost: 140 },
    { text: "Colonia Tepeyac por COHEP", cost: 100 },
    { text: "Llantera Las Casitas", cost: 90 },
    { text: "Flor del Campo por colegio Saúl Zelaya Jiménez", cost: 90 },
    { text: "Colonia Arturo Quezada arriba de Maxi Despensa", cost: 100 },
    { text: "Parada de buses Colonia Mary de Flores (orilla del anillo)", cost: 110 },
    { text: "Colonia Villa Los Laureles", cost: 100 },
    { text: "Coliseo de Ingenieros por Prados Universitarios", cost: 100 },
    { text: "Edificio Artemisa", cost: 100 },
    { text: "Campo Parada Martes", cost: 120 },
    { text: "Colonia El Sitio", cost: 130 },
    { text: "Colonia Divanna (se llega hasta El Santa)", cost: 100 },
    { text: "Lomas del Mayab", cost: 100 },
    { text: "Megalarach y Cía Miramontes", cost: 100 },
    { text: "Colonia Melgar segundo puente calle principal colonia Smith", cost: 100 },
    { text: "Residencial El Dorado", cost: 100 },
    { text: "Colonia Los Ángeles por Casamata", cost: 90 },
    { text: "Centroamérica Oeste", cost: 100 },
    { text: "Centroamérica Este", cost: 100 },
    { text: "Sagastume 2 (hasta parque Concordia)", cost: 110 },
    { text: "Pepetos Bella Vista", cost: 100 },
    { text: "Hospital Militar", cost: 130 },
    { text: "Colonia Villa Los Ciruelos por 28 de Marzo (calle principal)", cost: 100 },
    { text: "Colonia Villanueva carretera a Danlí (calle principal o 7 cuadras arriba de Villa de Sol)", cost: 160 },
    { text: "Residencial Honduras", cost: 100 },
    { text: "Hospital escuela", cost: 100 },
    { text: "Colonia travesía en el palo", cost: 100 },
    { text: "Barrio Villa Adela mercadito Quique", cost: 100 },
    { text: "Colonia El Prado calle principal", cost: 100 },
    { text: "Colonia Nueva Suyapa", cost: 110 },
    { text: "Residencial Centroamérica este", cost: 100 },
    { text: "Colonia 21 de octubre en codis", cost: 120 },
    { text: "Mercado jacaleapa", cost: 100 },
    { text: "La granja por el juzgado", cost: 100 },
    { text: "Colonia Santa Fe calle principal contiguo al punto de taxis", cost: 100 },
    { text: "Residencial bosques del tablón", cost: 130 },
    { text: "Desvío de aldea Santa Rosa", cost: 130 },
    { text: "Colonia Policarpo Paz", cost: 100 },
    { text: "Casa quinchón enfrente de finanza antes de parque La leona", cost: 100 },
    { text: "Residencial Francisco morazán", cost: 100 },
    { text: "A la orilla del anillo en la nueva capital", cost: 110 },
    { text: "Hato de enmedio", cost: 100 },
    { text: "Colonia modesto rodas #2 atrás de la escuela Fuerzas Armadas", cost: 120 },
    { text: "Barrio Buenos Aires calle principal frente a punto de taxi", cost: 110 },
    { text: "Barrio el rincón Arriba de la alcaldía municipal pasando la tranca hay unas pulperías y ahí hay una placita. Mi casa está frente a la placita", cost: 120 },
    { text: "Colonia calpules", cost: 100 },
    { text: "Gasolinera Puma frente al hospital San Felipe", cost: 100 },
    { text: "Colonia nueva esperanza calle principal esquina opuesta d colegio modelo por tiloarque a la par de posta de policía", cost: 100 },
    { text: "Honduras maya", cost: 100 },
    { text: "Aqui en el calffaa para mateo Después del campo parada martes", cost: 130 },
    { text: "Colonia San José de la peña media cuadra antes de la posta policial", cost: 100 },
    { text: "Gasolinera Puma de germania", cost: 120 },
    { text: "Barrio Guanacaste", cost: 100 },
    { text: "Maxi despensa de la Kennedy", cost: 100 },
    { text: "Palo de hule en el puente", cost: 100 },
    { text: "Lomas del guijarro", cost: 100 },
    { text: "Cerro grande zona 1", cost: 120 },
    { text: "En la divino paraíso (solo a orilla del anillo)", cost: 110 },
    { text: "Boulevard suyapa", cost: 100 },
    { text: "Residencial paseo las campanas arriba de la unitec", cost: 100 },
    { text: "hospital San Jorge", cost: 100 },
    { text: "Sushilab de la colonia América", cost: 90 },
    { text: "Gasolinera shell del anillo en loarque", cost: 90 },
    { text: "Complejo caprisa calle principal", cost: 100 },
    { text: "Colonia Los Llanos", cost: 90 },
    { text: "Centro comercial plaza Milenium", cost: 100 },
    { text: "Colonia Florencia, Edicio Plaza América, distribuidora san Rafael", cost: 100 },
    { text: "Pedragalito", cost: 100 },
    { text: "Mall El Dorado", cost: 100 },
    { text: "Colonia La Joya", cost: 100 },
    { text: "Residencial Centro America 4 etapa bloque 79", cost: 100 },
    { text: "Residencial Monte Verde", cost: 100 },
    { text: "Centro de Tegucigalpa, calle La Fuente, casa de esquina frente al parqueo", cost: 100 },
    { text: "Gasolinera Texaco salida a Danlí", cost: 130 },
    { text: "Residencial Villas de Oriente", cost: 160 },
    { text: "Colonia El Tablón, calle principal frente a la escuela", cost: 120 },
    { text: "Colonia Israel solo calle principal", cost: 110 },
    { text: "Calle frente a camosa entrada taller industrial y taller de motos", cost: 100 },
    { text: "Colonia Independencia solo calle principal", cost: 100 },
    { text: "Frente a cuarta estación policial del belen", cost: 100 },
    { text: "Gasolinera Shell de Loarque", cost: 90 },
    { text: "Colonia villa nueva sector la rampla solo orila calle principal", cost: 100 },
    { text: "Residencial Lomas de Germanía", cost: 120 },
    { text: "Hotel Honduras 3 en 7ma avenida", cost: 100 },
    { text: "Edificio rosental en miramontes", cost: 100 },
    { text: "Plaza la norteña", cost: 100 },
    { text: "Facultad de ciencias medicas en miramontes", cost: 100 },
    { text: "Colonia Los Pinos, calle principal, Los Panaderos Solo calle de la Honduras", cost: 120 },
    { text: "Colonia Iberia, calle principal, Solo se entrega en el puente", cost: 100 },
    { text: "Colonia nueva Danlí solo orilla de anillo", cost: 120 },
    { text: "Barrio el chile solo calle principal se entrega", cost: 100 },
    { text: "Motores Hino de Honduras (cerca de Ecoplaza, puente de la Villa Olímpica, a la par de Decora)", cost: 100 },
    { text: "Residencial Los Eucaliptos", cost: 100 },
    { text: "Secretaría de Seguridad, carretera a Mateo", cost: 120 },
    { text: "Base de los Cobras en 21 de Octubre", cost: 120 },
    { text: "Col. Argentina, dos cuadras antes de tienda de muebles Elements", cost: 100 },
    { text: "Bomberos del Carrizal", cost: 100 },
    { text: "Gasolinera Texaco del cruce de Mateo", cost: 100 },
    { text: "Comayagüela, Centro Comunal de Las Mercedes (a la par del kínder de Las Mercedes)", cost: 100 },
    { text: "Colonia Millenium Sur", cost: 90 },
    { text: "Colonia La Sosa solo calle principal", cost: 100 },
    { text: "Colonia Nueva australia en la quezada en reposteria grano de oro", cost: 100 },
    { text: "Colonia San Francisco solo calle principal", cost: 100 },
    { text: "Residencial El Molinón", cost: 100 },
    { text: "Colonia Villa Los Laureles (primera entrada)", cost: 100 },
    { text: "Aldea La Cañada (por la UTH, a la par de Intercontinental School, empresa Tekcom)", cost: 100 },
    { text: "Colonia Brisas del Norte solo calle principal", cost: 110 },
    { text: "Tizatillo solo calle principal por la posta", cost: 220 },
    { text: "Colonia La Reforma, empresa Sumitec", cost: 100 },
    { text: "Entrada de la colonia 3 de Mayo solo en entrada", cost: 110 },
    { text: "Colonia Tepeyac, Espresso Americano a la par de Canal 36", cost: 100 },
    { text: "Registro Nacional", cost: 110 },
    { text: "Banco Davivienda oficina principal", cost: 100 },
    { text: "Colonia Unidad y Fuerza (punto de mototaxis de la Australia, calle principal)", cost: 100 },
    { text: "Academia Militar carretera a Lepaterique", cost: 160 },
    { text: "Aldea de Suyapa hasta la iglesia / posta", cost: 100 },
    { text: "Altos de Santa Rosa hasta el cruce / entrada", cost: 140 },
    { text: "Barrio Casamata", cost: 120 },
    { text: "Barrio La Hoya antigua PC", cost: 100 },
    { text: "Barrio La Pagoda, antes de Plantas Tropicales del Boulevard Suyapa", cost: 100 },
    { text: "Barrio Perpetuo Socorro 12 calle Comayagüela por Transporte Congolón", cost: 100 },
    { text: "Barrio Perpetuo Socorro por Aguilar Paz", cost: 100 },
    { text: "Barrio San Rafael por el edificio rojo", cost: 100 },
    { text: "Bendeck Industrial segundo anillo frente a Prados Universitarios", cost: 100 },
    { text: "Breadco contiguo a Hertz Rent a Car / anillo periférico", cost: 100 },
    { text: "Brisas del Sol hasta La Mundial", cost: 100 },
    { text: "Campo Cielo calle principal", cost: 120 },
    { text: "Carrizal salida al norte puente Bienvenido a Tegucigalpa", cost: 120 },
    { text: "Cementerio General de Las Casitas", cost: 90 },
    { text: "Centro de salud Colonia Los Pinos", cost: 120 },
    { text: "Cerro Grande zona 2", cost: 120 },
    { text: "Cerro Grande zona 5", cost: 120 },
    { text: "Colonia 29 del anillo frente a Larach", cost: 100 },
    { text: "Colonia Alemán", cost: 90 },
    { text: "Colonia El Country / LTH del Country", cost: 100 },
    { text: "Colonia El Porvenir cerca de Barrio El Chile / hasta el puente", cost: 100 },
    { text: "Colonia El Rosario abajo de Mall Premier", cost: 100 },
    { text: "Colonia Izaguirre", cost: 100 },
    { text: "Colonia La Era hasta Distrito Central", cost: 100 },
    { text: "Colonia La Esperanza final del Boulevard Morazán", cost: 100 },
    { text: "Colonia La Peña contiguo a pulpería La Bendición", cost: 100 },
    { text: "Colonia Las Ayestas calle principal", cost: 100 },
    { text: "Colonia Las Mercedes tercera entrada", cost: 100 },
    { text: "Colonia Las Palmas", cost: 100 },
    { text: "Colonia Los Girasoles por la 21 de Octubre", cost: 120 },
    { text: "Colonia Los Pinos calle principal frente a Escuela Hermán Herrera Molina", cost: 120 },
    { text: "Colonia Los Profesores / iglesia La Cruz / tortillería Los Ángeles", cost: 100 },
    { text: "Colonia Montes de Bendición entrada mano izquierda Maxi Despensa", cost: 100 },
    { text: "Colonia Nueva Galilea hasta Maxi Despensa Quezada", cost: 100 },
    { text: "Colonia Nueva Jerusalén primera entrada Pollos La Antorcha", cost: 100 },
    { text: "Colonia Popular calle principal", cost: 100 },
    { text: "Colonia Primero de Diciembre", cost: 100 },
    { text: "Colonia Ramón Amaya Amador calle principal", cost: 100 },
    { text: "Colonia San Ángel", cost: 100 },
    { text: "Colonia San Buenaventura / Colegio Superación San Francisco", cost: 100 },
    { text: "Colonia San José de la Vega calle principal frente a Cinco Estrellas / Abarrotería La Bodeguita", cost: 100 },
    { text: "Colonia San Martín hasta Las Mercedes", cost: 100 },
    { text: "Colonia Santa María", cost: 130 },
    { text: "Colonia Santa María bloque 9C dos bloques después de iglesia mormona", cost: 130 },
    { text: "Colonia Venezuela sector A calle principal", cost: 100 },
    { text: "Complejo de la Policía Militar en Las Pozas", cost: 130 },
    { text: "Condominios Lomas del Country por colegio San Francisco / Bombas SANAA", cost: 100 },
    { text: "Denny's de Toncontín", cost: 90 },
    { text: "Destacamento militar represa Los Laureles", cost: 100 },
    { text: "Edificio SONISA Paseo Tres Caminos / Seguros Atlántida", cost: 100 },
    { text: "El Edén Comayagüela calle principal a Los Laureles", cost: 100 },
    { text: "El Manchén", cost: 110 },
    { text: "Escuela Técnica del Ejército frente al Cuartel General", cost: 130 },
    { text: "Fuerza Aérea", cost: 90 },
    { text: "Gasolinera Puma frente a Iglesia Guadalupe / Banco Occidente / ACOSA Bulevar Morazán", cost: 100 },
    { text: "Hotel Clarion", cost: 100 },
    { text: "Iglesia Casa de Dios Puerta al Cielo", cost: 0 },
    { text: "Industrial de Alimentos EYL", cost: 100 },
    { text: "Kínder Saúl Zelaya calle principal de La Sosa", cost: 100 },
    { text: "Las Torres Diprova", cost: 100 },
    { text: "Loarque Río Grande Sur", cost: 100 },
    { text: "Lomas de San José 1 etapa por Las Palmas / Texaco Kennedy", cost: 100 },
    { text: "Mayoreo tienda El Pacífico", cost: 100 },
    { text: "Parada de buses La Quezada / Clínica Azul / Cuerpo de Cristo", cost: 100 },
    { text: "Pasaje San Miguel sexta avenida Comayagüela", cost: 100 },
    { text: "Paseo Los Próceres frente a Hotel Hyatt Place / Diunsa Próceres", cost: 100 },
    { text: "Plantas Tropicales", cost: 100 },
    { text: "Plaza Lara por Próceres", cost: 100 },
    { text: "Plaza Macuelizo / Torre San Carlos", cost: 100 },
    { text: "Plaza Perisur adelante de Camosa", cost: 90 },
    { text: "Portal de Viera", cost: 130 },
    { text: "Posta Villa Vieja", cost: 160 },
    { text: "Primer Batallón de Infantería en Mateo a la par de COPECO", cost: 130 },
    { text: "Puente El Chile", cost: 100 },
    { text: "Punto mototaxi adelante del Motel Villa Nueva", cost: 110 },
    { text: "Reparto Abajo una cuadra arriba de Mercado San Pablo", cost: 110 },
    { text: "Residencial El Tablón", cost: 130 },
    { text: "Residencial Granada por Pedregalito", cost: 100 },
    { text: "Residencial Lomas de María Auxiliadora", cost: 130 },
    { text: "Residencial Monte Fresco por el puentón de Colonia El Edén", cost: 100 },
    { text: "Residencial Palma Real", cost: 90 },
    { text: "Residencial San Juan", cost: 100 },
    { text: "Residencial San Juan frente a Colonia Bella Oriente", cost: 100 },
    { text: "Residencial Santa María", cost: 130 },
    { text: "Residencial Vegas del Country", cost: 100 },
    { text: "Segunda Avenida de Comayagüela / Palacio de las Chumpas", cost: 100 },
    { text: "Segunda Avenida de Comayagüela esquina opuesta al Puente Mallol / Palo de Hule", cost: 100 },
    { text: "Shell del Anillo donde está Pizza Hut", cost: 100 },
    { text: "Supermercado La Colonia #1", cost: 100 },
    { text: "Supermercado Villas del Sol", cost: 100 },
    { text: "Teatro Manuel Bonilla", cost: 100 },
    { text: "Terminal de buses Nueva Suyapa hasta AGAFAM", cost: 100 },
    { text: "Texaco Cerro Grande antes de zona 8", cost: 130 },
    { text: "Texaco Santa Lucía", cost: 130 },
    { text: "Villa Centroamericana frente al Chochi Sosa", cost: 100 }
  ]
};
